[display]

[display.display]
SCK
MOSI
ecs_pin="CE0"
dc_pin="D22"
rst_pin="D27"
busy_pin="D17"
width_in_pixel=122
height_in_pixel=250
scale="landscape"


[display.views]


[buttons]
[buttons.D5]
action="action"

[buttons.D6]
action="cycle"
