[home_assistant]
url = "ws://homeassistant.local:8123/api/websocket"
token = ""
entities = []
update_timeout = 30

[display]
ecs_pin = "CE0"
dc_pin = "D22"
rst_pin = "D27"
busy_pin = "D17"
width_in_pixel = 122
height_in_pixel = 250

[buttons]
[buttons.D5]
action = "action"

[buttons.D6]
action = "cycle"
